COL object_path FORMAT A45

SELECT distinct(object_name), owner, object_type
    FROM all_objects
    WHERE object_name LIKE '%EXPORT_OBJECTS';

SELECT OBJECT_PATH, COMMENTS
    FROM SCHEMA_EXPORT_OBJECTS
    WHERE OBJECT_PATH LIKE '%GRANT' AND OBJECT_PATH NOT LIKE '%/%';

SELECT OBJECT_PATH, COMMENTS
    FROM DATABASE_EXPORT_OBJECTS
    WHERE OBJECT_PATH LIKE '%GRANT' AND OBJECT_PATH NOT LIKE '%/%';
