SET LINES 120
COL PCTUSED format A7
COL PCTRECL format A7
select FILE_TYPE, to_char(PERCENT_SPACE_USED, '99.9')        PCTUSED,
                  to_char(PERCENT_SPACE_RECLAIMABLE, '99.9') PCTRECL,
		NUMBER_OF_FILES FILES
from v$FLASH_RECOVERY_AREA_USAGE
/
