SET HEAD OFF
SET FEEDBACK OFF
SET ECHO OFF TERMOUT OFF
SET TRIMSPOOL ON
SET PAGES 0 LINES 2000
SET VERIFY OFF

SPOOL /tmp/killuser-out.sql REPLACE

SELECT 'ALTER SYSTEM DISCONNECT SESSION '''||sid||','||serial#||''' IMMEDIATE;'
    FROM gv$session
WHERE username=UPPER('&1');
SPOOL OFF

SET HEAD ON FEEDBACK ON TERMOUT ON
SET PAGES 40

@@/tmp/killuser-out.sql

