COL parameter FORMAT A30
COL value     FORMAT A30

PROMPT SESSION
SELECT * FROM nls_session_parameters;

PROMPT INSTANCE
select * FROM NLS_INSTANCE_PARAMETERS;

PROMPT DATABASE
select * from NLS_DATABASE_PARAMETERS;

