SET VERIFY OFF

COL OWNER FORMAT A10
COL GRANTEE FORMAT A10
COL GRANTOR FORMAT A10
COL PRIVILEGE FORMAT A10
COL TABLE_NAME FORMAT A20

SELECT * FROM DBA_TAB_PRIVS
WHERE table_name=upper('&1')
/

SET VERIFY ON

COL GRANTEE CLEAR
COL GRANTOR CLEAR
COL OWNER   CLEAR
COL PRIVILEGE CLEAR
COL TABLE_NAME  CLEAR
